import "./globals.css";
import { AuthProvider } from "./auth/authContext";

export const metadata = {
    title: "DoYourTasks",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
